const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopAPI", {
  pickFolder: () => ipcRenderer.invoke("dialog:pick-folder"),
  pickZip: () => ipcRenderer.invoke("dialog:pick-zip"),
  pickExtensionArchive: () => ipcRenderer.invoke("dialog:pick-extension-archive"),
  pickWorkspaceResource: () => ipcRenderer.invoke("dialog:pick-workspace-resource"),
  saveBackup: (siteName) => ipcRenderer.invoke("dialog:save-backup", siteName),
  browserCreateTab: (payload) => ipcRenderer.invoke("browser:create-tab", payload),
  browserActivateTab: (tabId) => ipcRenderer.invoke("browser:activate-tab", tabId),
  browserCloseTab: (tabId) => ipcRenderer.invoke("browser:close-tab", tabId),
  browserNavigate: (url) => ipcRenderer.invoke("browser:navigate", url),
  browserGetSuggestions: (query) => ipcRenderer.invoke("browser:get-suggestions", query),
  browserGoBack: () => ipcRenderer.invoke("browser:go-back"),
  browserGoForward: () => ipcRenderer.invoke("browser:go-forward"),
  browserReload: () => ipcRenderer.invoke("browser:reload"),
  browserAutofillCredentials: (payload) => ipcRenderer.invoke("browser:autofill-credentials", payload),
  browserShowAppMenu: (payload) => ipcRenderer.invoke("browser:show-app-menu", payload),
  browserFindInPage: (text) => ipcRenderer.invoke("browser:find-in-page", text),
  browserUpdateLayout: (payload) => ipcRenderer.invoke("browser:update-layout", payload),
  browserPickDownloadDirectory: () => ipcRenderer.invoke("browser:pick-download-directory"),
  browserOpenDownload: (downloadId) => ipcRenderer.invoke("browser:open-download", downloadId),
  browserShowDownload: (downloadId) => ipcRenderer.invoke("browser:show-download", downloadId),
  browserClearDownloads: () => ipcRenderer.invoke("browser:clear-downloads"),
  browserClearPermission: (payload) => ipcRenderer.invoke("browser:clear-permission", payload),
  browserAddBookmark: (payload) => ipcRenderer.invoke("browser:add-bookmark", payload),
  browserAddBookmarkFolder: (payload) => ipcRenderer.invoke("browser:add-bookmark-folder", payload),
  browserRemoveBookmark: (bookmarkId) => ipcRenderer.invoke("browser:remove-bookmark", bookmarkId),
  browserUpdateBookmark: (payload) => ipcRenderer.invoke("browser:update-bookmark", payload),
  browserMoveBookmark: (payload) => ipcRenderer.invoke("browser:move-bookmark", payload),
  browserCopyBookmark: (bookmarkId) => ipcRenderer.invoke("browser:copy-bookmark", bookmarkId),
  browserCutBookmark: (bookmarkId) => ipcRenderer.invoke("browser:cut-bookmark", bookmarkId),
  browserPasteBookmark: () => ipcRenderer.invoke("browser:paste-bookmark"),
  browserSetBookmarksBarVisible: (visible) => ipcRenderer.invoke("browser:set-bookmarks-bar-visible", visible),
  browserCreateWindow: (payload) => ipcRenderer.invoke("browser:create-window", payload),
  browserShowBookmarkContextMenu: (payload) => ipcRenderer.invoke("browser:show-bookmark-context-menu", payload),
  browserShowTabContextMenu: (tabId) => ipcRenderer.invoke("browser:show-tab-context-menu", tabId),
  browserSetTabNickname: (payload) => ipcRenderer.invoke("browser:set-tab-nickname", payload),
  browserSaveTabSession: (payload) => ipcRenderer.invoke("browser:save-tab-session", payload),
  browserUnsaveTabSession: (payload) => ipcRenderer.invoke("browser:unsave-tab-session", payload),
  browserShowBookmarkSaveDialog: (payload) => ipcRenderer.invoke("browser:show-bookmark-save-dialog", payload),
  testDb: (config) => ipcRenderer.invoke("db:test", config),
  installWordPress: (payload) => ipcRenderer.invoke("installer:run", payload),
  openPath: (targetPath) => ipcRenderer.invoke("shell:open-path", targetPath),
  listBackups: () => ipcRenderer.invoke("backups:list"),
  restoreBackup: (payload) => ipcRenderer.invoke("backups:restore", payload),
  copyWorkspaceMedia: (targetPath) => ipcRenderer.invoke("workspace:copy-media", targetPath),
  openWorkspaceMediaWith: (targetPath) => ipcRenderer.invoke("workspace:open-with", targetPath),
  listSites: () => ipcRenderer.invoke("sites:list"),
  backupSite: (payload) => ipcRenderer.invoke("sites:backup", payload),
  applyMultisiteConfig: (payload) => ipcRenderer.invoke("sites:apply-multisite-config", payload),
  deleteSite: (payload) => ipcRenderer.invoke("sites:delete", payload),
  showSiteContextMenu: (site) => ipcRenderer.invoke("sites:show-context-menu", site),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  getMcpServerStatus: () => ipcRenderer.invoke("mcp-server:get-status"),
  startMcpServer: (config) => ipcRenderer.invoke("mcp-server:start", config),
  stopMcpServer: () => ipcRenderer.invoke("mcp-server:stop"),
  setLocalServerType: (localServerType) => ipcRenderer.invoke("settings:set-local-server-type", localServerType),
  setLocalServerRootPath: (payload) => ipcRenderer.invoke("settings:set-local-server-root", payload),
  setXamppRootPath: (xamppRootPath) => ipcRenderer.invoke("settings:set-xampp-root", xamppRootPath),
  setHtdocsPath: (htdocsPath) => ipcRenderer.invoke("settings:set-htdocs", htdocsPath),
  setLocalSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-local-session-sharing", enabled),
  setOnlineSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-online-session-sharing", enabled),
  setSessionAutoSaveScope: (payload) => ipcRenderer.invoke("settings:set-session-autosave-scope", payload),
  setSessionAutoSaveDelay: (seconds) => ipcRenderer.invoke("settings:set-session-autosave-delay", seconds),
  saveMysqlConfig: (payload) => ipcRenderer.invoke("settings:save-mysql-config", payload),
  saveWpInstallDefaults: (payload) => ipcRenderer.invoke("settings:save-wp-install-defaults", payload),
  installBrowserExtensionFromFolder: (folderPath) => ipcRenderer.invoke("settings:install-browser-extension-folder", folderPath),
  installBrowserExtensionFromArchive: (archivePath) => ipcRenderer.invoke("settings:install-browser-extension-archive", archivePath),
  installBrowserExtensionFromStore: (input) => ipcRenderer.invoke("settings:install-browser-extension-store", input),
  updateStoreExtensions: () => ipcRenderer.invoke("settings:update-store-extensions"),
  parseExtensionStoreUrl: (input) => ipcRenderer.invoke("extensions:parse-store-url", input),
  setBrowserExtensionEnabled: (payload) => ipcRenderer.invoke("settings:set-browser-extension-enabled", payload),
  setBrowserExtensionPinned: (payload) => ipcRenderer.invoke("settings:set-browser-extension-pinned", payload),
  removeBrowserExtension: (extensionId) => ipcRenderer.invoke("settings:remove-browser-extension", extensionId),
  openBrowserExtensionPopup: (extensionId) => ipcRenderer.invoke("browser:open-extension-popup", extensionId),
  getVaultInfo: () => ipcRenderer.invoke("vault:get-info"),
  getInstallerDbProfile: () => ipcRenderer.invoke("vault:get-installer-db"),
  saveInstallerDbProfile: (profile) => ipcRenderer.invoke("vault:save-installer-db", profile),
  clearInstallerDbProfile: () => ipcRenderer.invoke("vault:clear-installer-db"),
  getSiteCredentials: (key) => ipcRenderer.invoke("vault:get-site-credentials", key),
  saveSiteCredentials: (payload) => ipcRenderer.invoke("vault:save-site-credentials", payload),
  clearSiteCredentials: (key) => ipcRenderer.invoke("vault:clear-site-credentials", key),
  onBrowserState: (handler) => ipcRenderer.on("browser:state", (_event, payload) => handler(payload)),
  onBrowserNotice: (handler) => ipcRenderer.on("browser:notice", (_event, payload) => handler(payload)),
  onBrowserMenuCommand: (handler) => ipcRenderer.on("browser:menu-command", (_event, payload) => handler(payload)),
  onBrowserDownloadComplete: (handler) => ipcRenderer.on("browser:download-complete", (_event, payload) => handler(payload)),
  setLocalSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-local-session-sharing", enabled),
  setOnlineSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-online-session-sharing", enabled),
  setSessionAutoSaveScope: (payload) => ipcRenderer.invoke("settings:set-session-autosave-scope", payload),
  setSessionAutoSaveDelay: (seconds) => ipcRenderer.invoke("settings:set-session-autosave-delay", seconds),
  saveMysqlConfig: (payload) => ipcRenderer.invoke("settings:save-mysql-config", payload),
  saveWpInstallDefaults: (payload) => ipcRenderer.invoke("settings:save-wp-install-defaults", payload),
  installBrowserExtensionFromFolder: (folderPath) => ipcRenderer.invoke("settings:install-browser-extension-folder", folderPath),
  installBrowserExtensionFromArchive: (archivePath) => ipcRenderer.invoke("settings:install-browser-extension-archive", archivePath),
  installBrowserExtensionFromStore: (input) => ipcRenderer.invoke("settings:install-browser-extension-store", input),
  updateStoreExtensions: () => ipcRenderer.invoke("settings:update-store-extensions"),
  parseExtensionStoreUrl: (input) => ipcRenderer.invoke("extensions:parse-store-url", input),
  setBrowserExtensionEnabled: (payload) => ipcRenderer.invoke("settings:set-browser-extension-enabled", payload),
  setBrowserExtensionPinned: (payload) => ipcRenderer.invoke("settings:set-browser-extension-pinned", payload),
  removeBrowserExtension: (extensionId) => ipcRenderer.invoke("settings:remove-browser-extension", extensionId),
  openBrowserExtensionPopup: (extensionId) => ipcRenderer.invoke("browser:open-extension-popup", extensionId),
  getVaultInfo: () => ipcRenderer.invoke("vault:get-info"),
  getInstallerDbProfile: () => ipcRenderer.invoke("vault:get-installer-db"),
  saveInstallerDbProfile: (profile) => ipcRenderer.invoke("vault:save-installer-db", profile),
  clearInstallerDbProfile: () => ipcRenderer.invoke("vault:clear-installer-db"),
  getSiteCredentials: (key) => ipcRenderer.invoke("vault:get-site-credentials", key),
  saveSiteCredentials: (payload) => ipcRenderer.invoke("vault:save-site-credentials", payload),
  clearSiteCredentials: (key) => ipcRenderer.invoke("vault:clear-site-credentials", key),
  onBrowserState: (handler) => ipcRenderer.on("browser:state", (_event, payload) => handler(payload)),
  onBrowserNotice: (handler) => ipcRenderer.on("browser:notice", (_event, payload) => handler(payload)),
  onBrowserMenuCommand: (handler) => ipcRenderer.on("browser:menu-command", (_event, payload) => handler(payload)),
  onBrowserDownloadComplete: (handler) => ipcRenderer.on("browser:download-complete", (_event, payload) => handler(payload)),
  onBrowserBookmarkEdit: (handler) => ipcRenderer.on("browser:bookmark-edit", (_event, payload) => handler(payload)),
  onBrowserBookmarkFolderEdit: (handler) => ipcRenderer.on("browser:bookmark-folder-edit", (_event, payload) => handler(payload)),
  onBrowserBookmarkFolderOpen: (handler) => ipcRenderer.on("browser:bookmark-folder-open", (_event, payload) => handler(payload)),
  onBrowserBookmarkFolderAddChild: (handler) => ipcRenderer.on("browser:bookmark-folder-add-child", (_event, payload) => handler(payload)),
  onBrowserBookmarkManage: (handler) => ipcRenderer.on("browser:bookmark-manage", () => handler()),
  onBrowserBookmarkCreateFolderAndMove: (handler) => ipcRenderer.on("browser:bookmark-create-folder-and-move", (_event, payload) => handler(payload)),
  onBrowserOpenUrl: (handler) => ipcRenderer.on("browser:open-url", (_event, payload) => handler(payload)),
  onBrowserFocus: (handler) => ipcRenderer.on("browser:focus", () => handler()),
  browserToggleFullscreen: () => ipcRenderer.invoke("browser:toggle-fullscreen"),
  onBrowserFullscreenChanged: (handler) => ipcRenderer.on("browser:fullscreen-changed", (_event, isFullscreen) => handler(isFullscreen)),
  onPromptSaveCredentials: (handler) => ipcRenderer.on("browser:prompt-save-credentials", (_event, payload) => handler(payload)),
  syncGetStatus: () => ipcRenderer.invoke("sync:get-status"),
  syncAuthGoogle: () => ipcRenderer.invoke("sync:auth-google"),
  syncAuthMicrosoft: () => ipcRenderer.invoke("sync:auth-microsoft"),
  syncDisconnectGoogle: () => ipcRenderer.invoke("sync:disconnect-google"),
  syncDisconnectMicrosoft: () => ipcRenderer.invoke("sync:disconnect-microsoft"),
  onSitesChanged: (handler) => ipcRenderer.on("sites:changed", () => handler()),
  pickFile: () => ipcRenderer.invoke("dialog:pick-file"),
  saveFile: (defaultPath) => ipcRenderer.invoke("dialog:save-file", defaultPath),
  writeFile: (payload) => ipcRenderer.invoke("file:write", payload),
  saveSftpConfig: (siteId, config) => ipcRenderer.invoke("sftp:save-config", { siteId, config }),
  testSftpConnection: (config) => ipcRenderer.invoke("sftp:test", config),
  startSftpTransfer: (payload) => ipcRenderer.invoke("sftp:transfer", payload),
  getSftpServerStatus: () => ipcRenderer.invoke("sftp-server:get-status"),
  saveSftpServerSettings: (config) => ipcRenderer.invoke("sftp-server:save-settings", config),
  startSftpServer: (config) => ipcRenderer.invoke("sftp-server:start", config),
  stopSftpServer: () => ipcRenderer.invoke("sftp-server:stop"),
  onSftpProgress: (handler) => ipcRenderer.on("sftp:progress", (_event, payload) => handler(payload)),
  listSftpDirectory: (connectionId, remotePath) => ipcRenderer.invoke("sftp:list-dir", { connectionId, remotePath }),
  readSftpFile: (connectionId, remotePath) => ipcRenderer.invoke("sftp:read-file", { connectionId, remotePath }),
  closeSftpConnection: (connectionId) => ipcRenderer.invoke("sftp:close-connection", connectionId),
  readExtensionFile: (filePath) => ipcRenderer.invoke("extensions:read-file", filePath),
  getDesktopSources: () => ipcRenderer.invoke("meeting:get-sources"),

  // ── Tailscale Admin Toolkit ────────────────────────────────────────
  tailscaleDetect:          ()          => ipcRenderer.invoke("tailscale:detect"),
  tailscaleStatus:          ()          => ipcRenderer.invoke("tailscale:status"),
  tailscalePeers:           ()          => ipcRenderer.invoke("tailscale:peers"),
  tailscalePing:            (host)      => ipcRenderer.invoke("tailscale:ping", host),
  tailscaleSsh:             (payload)   => ipcRenderer.invoke("tailscale:ssh", payload),
  tailscaleRdp:             (ip)        => ipcRenderer.invoke("tailscale:rdp", ip),
  tailscaleWhois:           (ip)        => ipcRenderer.invoke("tailscale:whois", ip),
  tailscaleExitNodes:       ()          => ipcRenderer.invoke("tailscale:exit-nodes"),
  tailscaleSetExitNode:     (node)      => ipcRenderer.invoke("tailscale:set-exit-node", node),
  tailscaleServeStatus:     ()          => ipcRenderer.invoke("tailscale:serve-status"),
  tailscaleServeAdd:        (payload)   => ipcRenderer.invoke("tailscale:serve-add", payload),
  tailscaleServeRemove:     (payload)   => ipcRenderer.invoke("tailscale:serve-remove", payload),
  tailscaleFunnelStatus:    ()          => ipcRenderer.invoke("tailscale:funnel-status"),
  tailscaleFunnelSet:       (payload)   => ipcRenderer.invoke("tailscale:funnel-set", payload),
  tailscaleNetcheck:        ()          => ipcRenderer.invoke("tailscale:netcheck"),
  tailscaleDns:             ()          => ipcRenderer.invoke("tailscale:dns"),
  tailscaleLogin:           ()          => ipcRenderer.invoke("tailscale:login"),
  tailscaleLogout:          ()          => ipcRenderer.invoke("tailscale:logout"),
  tailscaleRunCommand:      (args)      => ipcRenderer.invoke("tailscale:run-command", args),
  tailscaleFileSend:        (payload)   => ipcRenderer.invoke("tailscale:file-send", payload),
  tailscaleFilePick:        ()          => ipcRenderer.invoke("tailscale:file-pick"),
  tailscaleCertGet:         (hostname)  => ipcRenderer.invoke("tailscale:cert-get", hostname),
  tailscaleMetrics:         ()          => ipcRenderer.invoke("tailscale:metrics"),
  tailscaleStartMonitor:    (ms)        => ipcRenderer.invoke("tailscale:start-monitor", ms),
  tailscaleStopMonitor:     ()          => ipcRenderer.invoke("tailscale:stop-monitor"),
  onTailscalePeerUpdate:    (handler)   => ipcRenderer.on("tailscale:peer-update",    (_e, p) => handler(p)),
  onTailscaleNotification:  (handler)   => ipcRenderer.on("tailscale:notification",   (_e, p) => handler(p)),
  openExternal:             (url)       => ipcRenderer.invoke("shell:open-external", url),
  shellRun:                 (payload)   => ipcRenderer.invoke("shell:run", payload),
  dbQuery:                  (payload)   => ipcRenderer.invoke("db:query", payload),
});
