const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("desktopAPI", {
  pickFolder: () => ipcRenderer.invoke("dialog:pick-folder"),
  pickZip: () => ipcRenderer.invoke("dialog:pick-zip"),
  saveBackup: (siteName) => ipcRenderer.invoke("dialog:save-backup", siteName),
  browserCreateTab: (payload) => ipcRenderer.invoke("browser:create-tab", payload),
  browserActivateTab: (tabId) => ipcRenderer.invoke("browser:activate-tab", tabId),
  browserCloseTab: (tabId) => ipcRenderer.invoke("browser:close-tab", tabId),
  browserNavigate: (url) => ipcRenderer.invoke("browser:navigate", url),
  browserGetSuggestions: (query) => ipcRenderer.invoke("browser:get-suggestions", query),
  browserGoBack: () => ipcRenderer.invoke("browser:go-back"),
  browserGoForward: () => ipcRenderer.invoke("browser:go-forward"),
  browserReload: () => ipcRenderer.invoke("browser:reload"),
  browserAutofillCredentials: (payload) => ipcRenderer.invoke("browser:autofill-credentials", payload),
  browserShowAppMenu: (payload) => ipcRenderer.invoke("browser:show-app-menu", payload),
  browserFindInPage: (text) => ipcRenderer.invoke("browser:find-in-page", text),
  browserUpdateLayout: (payload) => ipcRenderer.invoke("browser:update-layout", payload),
  browserPickDownloadDirectory: () => ipcRenderer.invoke("browser:pick-download-directory"),
  browserOpenDownload: (downloadId) => ipcRenderer.invoke("browser:open-download", downloadId),
  browserShowDownload: (downloadId) => ipcRenderer.invoke("browser:show-download", downloadId),
  browserClearDownloads: () => ipcRenderer.invoke("browser:clear-downloads"),
  browserClearPermission: (payload) => ipcRenderer.invoke("browser:clear-permission", payload),
  browserAddBookmark: (payload) => ipcRenderer.invoke("browser:add-bookmark", payload),
  browserAddBookmarkFolder: (payload) => ipcRenderer.invoke("browser:add-bookmark-folder", payload),
  browserRemoveBookmark: (bookmarkId) => ipcRenderer.invoke("browser:remove-bookmark", bookmarkId),
  browserUpdateBookmark: (payload) => ipcRenderer.invoke("browser:update-bookmark", payload),
  browserCopyBookmark: (bookmarkId) => ipcRenderer.invoke("browser:copy-bookmark", bookmarkId),
  browserCutBookmark: (bookmarkId) => ipcRenderer.invoke("browser:cut-bookmark", bookmarkId),
  browserPasteBookmark: () => ipcRenderer.invoke("browser:paste-bookmark"),
  browserSetBookmarksBarVisible: (visible) => ipcRenderer.invoke("browser:set-bookmarks-bar-visible", visible),
  browserCreateWindow: (payload) => ipcRenderer.invoke("browser:create-window", payload),
  browserShowBookmarkContextMenu: (payload) => ipcRenderer.invoke("browser:show-bookmark-context-menu", payload),
  browserShowTabContextMenu: (tabId) => ipcRenderer.invoke("browser:show-tab-context-menu", tabId),
  browserSetTabNickname: (payload) => ipcRenderer.invoke("browser:set-tab-nickname", payload),
  browserShowBookmarkSaveDialog: (payload) => ipcRenderer.invoke("browser:show-bookmark-save-dialog", payload),
  testDb: (config) => ipcRenderer.invoke("db:test", config),
  installWordPress: (payload) => ipcRenderer.invoke("installer:run", payload),
  openPath: (targetPath) => ipcRenderer.invoke("shell:open-path", targetPath),
  listSites: () => ipcRenderer.invoke("sites:list"),
  backupSite: (payload) => ipcRenderer.invoke("sites:backup", payload),
  deleteSite: (payload) => ipcRenderer.invoke("sites:delete", payload),
  showSiteContextMenu: (site) => ipcRenderer.invoke("sites:show-context-menu", site),
  getSettings: () => ipcRenderer.invoke("settings:get"),
  setXamppRootPath: (xamppRootPath) => ipcRenderer.invoke("settings:set-xampp-root", xamppRootPath),
  setHtdocsPath: (htdocsPath) => ipcRenderer.invoke("settings:set-htdocs", htdocsPath),
  setLocalSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-local-session-sharing", enabled),
  setOnlineSessionSharing: (enabled) => ipcRenderer.invoke("settings:set-online-session-sharing", enabled),
  saveMysqlConfig: (payload) => ipcRenderer.invoke("settings:save-mysql-config", payload),
  saveWpInstallDefaults: (payload) => ipcRenderer.invoke("settings:save-wp-install-defaults", payload),
  getVaultInfo: () => ipcRenderer.invoke("vault:get-info"),
  getInstallerDbProfile: () => ipcRenderer.invoke("vault:get-installer-db"),
  saveInstallerDbProfile: (profile) => ipcRenderer.invoke("vault:save-installer-db", profile),
  clearInstallerDbProfile: () => ipcRenderer.invoke("vault:clear-installer-db"),
  getSiteCredentials: (key) => ipcRenderer.invoke("vault:get-site-credentials", key),
  saveSiteCredentials: (payload) => ipcRenderer.invoke("vault:save-site-credentials", payload),
  clearSiteCredentials: (key) => ipcRenderer.invoke("vault:clear-site-credentials", key),
  onBrowserState: (handler) => ipcRenderer.on("browser:state", (_event, payload) => handler(payload)),
  onBrowserNotice: (handler) => ipcRenderer.on("browser:notice", (_event, payload) => handler(payload)),
  onBrowserMenuCommand: (handler) => ipcRenderer.on("browser:menu-command", (_event, payload) => handler(payload)),
  onBrowserDownloadComplete: (handler) => ipcRenderer.on("browser:download-complete", (_event, payload) => handler(payload)),
  onBrowserBookmarkEdit: (handler) => ipcRenderer.on("browser:bookmark-edit", (_event, payload) => handler(payload)),
  onBrowserBookmarkManage: (handler) => ipcRenderer.on("browser:bookmark-manage", () => handler()),
  onBrowserOpenUrl: (handler) => ipcRenderer.on("browser:open-url", (_event, payload) => handler(payload)),
  onBrowserFocus: (handler) => ipcRenderer.on("browser:focus", () => handler()),
  onSitesChanged: (handler) => ipcRenderer.on("sites:changed", () => handler())
});
